name: Nuget deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version of the nuget"
        required: true
        type: string
jobs:
  tagged-release:
    name: "Deploy to nuget.org"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - run: dotnet pack desseract.csproj --configuration Release -o out /p:Version=${{ github.event.inputs.version }}

      - name: Push the nuget
        run: dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
          
